name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm install
      - run: cp env.example .env
      - if: matrix.os == 'ubuntu-latest'
        run: npm run test-ci
      - run: npm run build
